In [1]:
import pandas as pd
import random

In [2]:
dataset_path        = '../data/processed/28714514_2021UKCensus_processed_20251009001.parquet'
dataset_nickname    = 'ukc2021-proc20251009001'
shuffled_path       = '../data/processed/28714514_2021UKCensus_processed_20251009001rs.parquet'

In [3]:
input_dataset = pd.read_parquet(dataset_path)
print(f"Dataset index: {input_dataset.index.name}, shape: {input_dataset.shape}")
input_dataset

Dataset index: OA, shape: (239023, 171)

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
OA,,,,,,,,,,,,,,,,,,,,,
E00000001,1.0,0.209183,0.640868,0.243536,0.169345,0.103164,0.366797,0.470588,0.601493,0.631579,...,0.285029,0.000000,0.310800,0.888200,0.000000,1.000000,0.000000,0.229715,0.000000,0.522534
E00000003,1.0,0.309635,0.645161,0.020326,0.081774,0.086102,0.251195,0.407407,0.656334,0.680556,...,0.345944,0.456294,0.000000,0.856471,0.000000,1.000000,0.000000,0.631733,0.112303,0.721809
E00000005,1.0,0.406816,0.426705,0.166442,0.186006,0.123386,0.418511,0.346154,0.550035,0.685714,...,0.175098,0.580362,0.000000,0.764779,0.540969,1.000000,0.387720,0.450933,0.218938,0.531674
E00000007,1.0,0.714259,0.224682,0.063464,0.056738,0.067209,0.436292,0.081081,0.493789,0.744186,...,0.378986,0.514418,0.542345,0.847968,0.000000,0.746280,0.270946,0.581465,0.000000,0.798493
E00000010,1.0,0.774129,0.182636,0.025794,0.092241,0.010926,0.760563,0.177083,0.193226,0.884615,...,0.337539,0.340955,0.418264,0.670164,0.000000,0.744087,0.000000,0.392793,0.144368,0.691696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W00010693,0.0,0.948568,0.018945,0.023874,0.045356,0.015170,0.800593,0.533333,0.111910,0.857143,...,0.467381,0.385012,0.000000,0.756641,0.000000,0.376339,0.251491,1.000000,0.957164,0.988956
W00010694,1.0,0.303494,0.577429,0.029018,0.181600,0.116776,0.234507,0.567568,0.708929,0.736842,...,0.190527,0.000000,0.000000,0.368474,0.000000,0.000000,0.152941,0.584291,0.439580,0.649834
W00010695,1.0,0.263569,0.600592,0.084821,0.164305,0.143725,0.246669,0.777778,0.657965,0.836735,...,0.000000,0.130488,1.000000,0.218686,0.000000,0.000000,0.000000,0.451619,0.365476,0.531674
W00010696,1.0,0.309869,0.617113,0.074338,0.121844,0.073477,0.211268,0.150000,0.746894,0.888889,...,0.000000,0.345142,0.000000,0.364166,0.000000,0.252971,0.225321,0.484348,0.404277,0.594223
W00010697,1.0,0.506067,0.349003,0.061260,0.237329,0.069201,0.315862,0.236842,0.651461,0.825000,...,0.000000,0.365155,0.000000,0.480921,0.000000,0.208073,0.000000,0.441907,0.113743,0.632958

In [4]:
seed = random.randint(100, 100000)
seed

83566

In [5]:
shuffled_dataset = input_dataset.sample(frac=1, replace=False, random_state=seed)
shuffled_dataset

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
OA,,,,,,,,,,,,,,,,,,,,,
E00071085,1.000000,0.305556,0.572115,0.068917,0.215650,0.072985,0.152113,0.611111,0.814389,0.693878,...,0.000000,0.223937,0.427451,0.146423,0.000000,0.000000,0.000000,0.523080,0.478946,0.507327
E00177567,1.000000,0.633985,0.321839,0.050698,0.079320,0.032214,0.264544,0.166667,0.614839,0.666667,...,0.661007,0.356224,0.642472,0.428904,0.000000,0.609488,0.375846,0.509519,0.455178,0.626352
E00039966,1.000000,0.308138,0.661796,0.024641,0.121163,0.020876,0.172855,0.266667,0.827428,0.821918,...,0.000000,0.362560,0.000000,0.384673,0.000000,0.000000,0.000000,0.532128,0.340561,0.581545
E00155752,0.469484,0.400431,0.475673,0.109099,0.202043,0.059420,0.365070,0.222222,0.574783,0.724138,...,0.402945,0.073309,0.211627,0.683376,0.000000,0.307746,0.000000,0.566563,0.237234,0.685577
E00018981,1.000000,0.251574,0.710547,0.060628,0.054204,0.089890,0.175998,0.666667,0.715518,0.747126,...,0.827517,0.782768,0.000000,0.146423,0.699728,0.208073,0.176281,0.581465,0.289491,0.651806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E00162823,1.000000,0.193732,0.766900,0.033415,0.089621,0.077851,0.088181,0.700000,0.911963,0.838095,...,0.000000,0.227468,0.260426,0.255916,0.000000,0.000000,0.000000,0.597494,0.550560,0.616580
S00164841,1.000000,0.320912,0.653333,0.000000,0.118300,0.024912,0.221467,0.157895,0.743985,0.861538,...,0.294459,0.115057,0.000000,0.000000,0.000000,0.000000,0.000000,0.306222,0.164451,0.362169
S00152701,1.000000,0.713566,0.207101,0.127232,0.113750,0.017966,0.384123,0.080000,0.601167,0.825000,...,0.000000,0.000000,0.407291,0.536659,0.518283,0.000000,0.293425,0.492251,0.462643,0.661991
E00173525,1.000000,0.817992,0.153846,0.040652,0.054516,0.008610,0.489558,0.042857,0.266867,0.800000,...,0.499093,0.289608,0.000000,0.922620,0.494812,0.715113,0.000000,0.899957,0.697707,0.929749
S00180245,1.000000,0.216524,0.758741,0.050122,0.044810,0.084928,0.253521,0.636364,0.746894,0.818182,...,0.000000,0.221640,1.000000,0.586183,0.985716,0.000000,0.000000,0.568975,0.411155,0.639806

In [6]:
for c in input_dataset.columns:
    assert input_dataset.loc['E00000001'][c] == shuffled_dataset.loc['E00000001'][c]
for c in input_dataset.columns:
    assert input_dataset.loc['E00147122'][c] == shuffled_dataset.loc['E00147122'][c]
for c in input_dataset.columns:
    assert input_dataset.loc['S00137206'][c] == shuffled_dataset.loc['S00137206'][c]

In [7]:
input_dataset.describe()

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
count,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,...,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000
mean,0.913986,0.377377,0.476768,0.104541,0.182604,0.120820,0.316694,0.436911,0.618733,0.661877,...,0.267227,0.271875,0.172684,0.409202,0.110047,0.198709,0.158024,0.520730,0.343857,0.547444
std,0.267273,0.139140,0.151686,0.073251,0.080058,0.080015,0.134729,0.211280,0.138510,0.116806,...,0.293188,0.224589,0.263879,0.239655,0.248704,0.246810,0.223380,0.148463,0.197195,0.182815
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.273504,0.367949,0.054230,0.128238,0.069201,0.222604,0.281250,0.541999,0.592233,...,0.000000,0.085494,0.000000,0.251667,0.000000,0.000000,0.000000,0.443548,0.209962,0.472794
50%,1.000000,0.359229,0.484830,0.092857,0.174857,0.107381,0.292056,0.439024,0.642277,0.666667,...,0.178171,0.244564,0.000000,0.405429,0.000000,0.126549,0.000000,0.524337,0.351221,0.570100
75%,1.000000,0.458480,0.594164,0.140767,0.227217,0.154780,0.386417,0.592593,0.715939,0.736111,...,0.480142,0.415997,0.266104,0.565057,0.000000,0.351778,0.286325,0.601882,0.470229,0.657851
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
shuffled_dataset.describe()

,uk001002_ntot_clipd_minmax,uk002002_ntot_noout_minmax,uk002003_ntot_noout_minmax,uk002004_ntot_clipd_minmax,uk002005_ntot_noout_minmax,uk002006_ntot_clipd_minmax,uk003002_ntot_noout_minmax,uk003003_ntot_noout_minmax,uk003005_ntot_noout_minmax,uk003006_ntot_noout_minmax,...,uk030005_ntot_clipd_ihs_minmax,uk030006_ntot_clipd_ihs_minmax,uk046004_ntot_clipd_ihs_minmax,uk046005_ntot_clipd_ihs_minmax,uk046009_ntot_clipd_ihs_minmax,uk046010_ntot_clipd_ihs_minmax,uk061006_ntot_clipd_ihs_minmax,uk062010_ntot_clipd_ihs_minmax,uk066008_ntot_clipd_ihs_minmax,uk066016_ntot_noout_ihs_minmax
count,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,...,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000,239023.000000
mean,0.913986,0.377377,0.476768,0.104541,0.182604,0.120820,0.316694,0.436911,0.618733,0.661877,...,0.267227,0.271875,0.172684,0.409202,0.110047,0.198709,0.158024,0.520730,0.343857,0.547444
std,0.267273,0.139140,0.151686,0.073251,0.080058,0.080015,0.134729,0.211280,0.138510,0.116806,...,0.293188,0.224589,0.263879,0.239655,0.248704,0.246810,0.223380,0.148463,0.197195,0.182815
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.273504,0.367949,0.054230,0.128238,0.069201,0.222604,0.281250,0.541999,0.592233,...,0.000000,0.085494,0.000000,0.251667,0.000000,0.000000,0.000000,0.443548,0.209962,0.472794
50%,1.000000,0.359229,0.484830,0.092857,0.174857,0.107381,0.292056,0.439024,0.642277,0.666667,...,0.178171,0.244564,0.000000,0.405429,0.000000,0.126549,0.000000,0.524337,0.351221,0.570100
75%,1.000000,0.458480,0.594164,0.140767,0.227217,0.154780,0.386417,0.592593,0.715939,0.736111,...,0.480142,0.415997,0.266104,0.565057,0.000000,0.351778,0.286325,0.601882,0.470229,0.657851
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
shuffled_dataset.to_parquet(shuffled_path)